### ISSUE TITLE
Can I Create Stomp-Server Over WebSocket here

### ISSUE THREAD

**Issue by Shub1427** [4ib3r/StompBrokerJS#1]
I am confused about creating a server in NodeJS that can act as a broker sing STOMP protocol over WebSockets... Can this Library help me with that??

**Comment by rpoitras** [comment]
@Shub1427 ... not sure if you still have this question.  What you are describing is exactly what this library is providing.

**Comment by ypetya** [comment]
Maybe you have problems with the underlying websocket library. It is supporting `ws`. I attempt to extend it for `sockjs`

**Comment by 4ib3r** [comment]
Please see an example from the `examples/sockjs` directory
