### ISSUE TITLE
ReferenceError: headers is not defined

### ISSUE THREAD

**Issue by geomen888** [4ib3r/StompBrokerJS#12]
hi
stompServer.subscribe('/**', function (msg, headers) {
  var topic = headers.destination
  console.log(topic, '->', msg)
}, headers) <-- problem with this particular "headers"

waiting advise, thank U

**Comment by mmatin-a** [comment]
have the same problem

> hi
> stompServer.subscribe('/**', function (msg, headers) {
> var topic = headers.destination
> console.log(topic, '->', msg)
> }, headers) <-- problem with this particular "headers"
> 
> waiting advise, thank U

**Comment by socks4penguins** [comment]
Same thing, kinda weird that the main example doesn't work

**Comment by 4ib3r** [comment]
Example is fixed for now
