### ISSUE TITLE
The SockJS example is not working

### ISSUE THREAD

**Issue by bjdash** [4ib3r/StompBrokerJS#17]
The example fails during handshake. **/ws** url is returning **404** . Refer below image:

![image](https://user-images.githubusercontent.com/4252908/43521279-3fd89524-95b3-11e8-84e3-3a3de2e225a4.png)

**Comment by ypetya** [comment]
Can you please try to remove the package-lock.json from `examples/sockjs` ?

The following works on my dev-env, with chrome browser.

1. checking out the master branch
2. npm install in the root project dir
3. remove `package-lock.json` from `examples/sockjs` directory
4. npm install in the `examples/sockjs` directory
5. run it with `npm start` in `examples/sockjs` directory
6. ensure console listening on port 3002
7. opening the browser

**Comment by 4ib3r** [comment]
Fixed
