### ISSUE TITLE
Please, refresh package in npm.

### ISSUE THREAD

**Issue by nuveum** [4ib3r/StompBrokerJS#18]
Currently, it contains version without SockJS adapter

**Comment by lavor** [comment]
What about this? In npm there is a version from April 5, but sockJS was introduced in April 23. Can you please publish the current repository version (April 23) into npm?

**Comment by nuveum** [comment]
Actual version of StompBrockerJs in npm doesn't contain sockJs adapter. So, yes, I'm asking to publish the current repository version into npm)))

**Comment by lavor** [comment]
Yeah, I got it. I am just another package consumer. I am asking the same.

**Comment by ypetya** [comment]
@4ib3r please, take a look!

**Comment by lavor** [comment]
I will be waiting for update in npm, but for now it works, thanks @ypetya .

**Comment by 4ib3r** [comment]
Version 1.3.0 is published.
