### ISSUE TITLE
need to send individual message to client

### ISSUE THREAD

**Issue by krtl** [4ib3r/StompBrokerJS#5]
Please implement sending of individual messages to stomp client.
Great thanks for your work!

**Comment by krtl** [comment]
I figured out how to do it

**Comment by bjdash** [comment]
@krtl Could you please share how you did it?

**Comment by krtl** [comment]
Unfortunately, I've done this by amending stompServer.js

2018-08-01 14:07 GMT+03:00 Bijay Dash <notifications@github.com>:

**Comment by krtl** [comment]
ok, I made two things:

1) add socket param to emit of 'send' event line 112 in original stompServer.js:
this.emit('send', {frame: {headers: frame.headers, body: bodyObj}, dest: args.dest, socket});

2) add following func to original stompServer.js

  /** SendIndividual message to specific client
   * @param {socket} client
   * @param {object} headers Message headers
   * @param {string} body Message body */
  this.sendIndividual = function (socket, topic, headers, body) {
    var _headers = {};
    if (headers) {
      for (var key in headers) {
        _headers[key] = headers[key];
      }
    }
    var frame = {
      body: body,
      headers: _headers
    };
    var args = {
      dest: topic,
      frame: this.frameParser(frame)
    };

    var bodyObj = args.frame.body;
    var frame = this.frameSerializer(args.frame);
    var headers = { //default headers
      'message-id': stomp.genId("msg"),
      'content-type': 'text/plain'
    };
    if (frame.body !== undefined) {
      if (typeof frame.body !== 'string')
        throw "Message body is not string";
      frame.headers["content-length"] = frame.body.length;
    }
    if (frame.headers) {
      for (var key in frame.headers) {
        headers[key] = frame.headers[key];
      }
    }

    for (var i in this.subscribes) {
      var sub = this.subscribes[i];
      if (socket.sessionId !== sub.sessionId) {
        continue;
      }
      var match = this._checkSubMatchDest(sub, args);
      if (match) {
        args.frame.headers.subscription = sub.id;
        frame.command = "MESSAGE";
        if (socket !== undefined) {
          StompUtils.sendFrame(socket, frame);
        }
      }
    }
  };




Usage: In my project I needed only to reply to individuals:

  stompServer.on('send', (ev) => {
           //...
           stompServer.sendIndividual(ev.socket, TOPIC_NAME, {}, REPLY_TEXT);
  });


the same code for reply on subscribe:

stompServer.on('subscribe', (ev) => {
           //...
           stompServer.sendIndividual(ev.socket, TOPIC_NAME, {}, REPLY_TEXT);
  });
